FROM lochnair/base:alpine
MAINTAINER Lochnair <me@lochnair.net>

LABEL Description="Docker base image based on Alpine Linux, with glibc compat"

RUN apk add \
    --no-cache \
    --update \
    libc6-compat