#!/usr/bin/with-contenv bash

PUID=${PUID:-313}
PGID=${PGID:-313}

chown -R $PUID:$PGID /app
chown -R $PUID:$PGID /config

echo "
--------- 90-fix-perms -----------
Fixed /app folder permissions
Fixed /config folder permissions
----------------------------------
"