#!/usr/bin/with-contenv bash

TZ=${TZ:-UTC}

echo "
--------- 20-set-timezone --------
Set timezone to: $TZ"

if [ ! -e /usr/share/zoneinfo/$TZ ]; then
	echo "Invalid timezone! Defaulting to UTC."
	TZ="UTC"
fi

echo "----------------------------------"

ln -sf /usr/share/zoneinfo/$TZ /etc/localtime
echo $TZ > /etc/timezone
export TZ=$TZ